name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd server
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install
          npm run build

      - name: Build Docker Images
        run: docker compose build

      - name: Deploy
        run: echo "Deploying application..."