name: Hello World

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo " a demo build "

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test phase
        run: echo "running test case"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deply the app
        run: echo "deploying the app"
        
