name: Hello World

on: workflow_dispatch

jobs:
  helokarthik:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: |
         echo " this is line one "
         echo "tis is line two"
         echo "tis is line four"
         echo "tis is line three"
        
